export const ACTIVITY_LIST = [
  {
    id: '0001',
    name: 'Test 1',
    date: new Date(2021, 4, 20, 19, 53, 26).toISOString(),
    duration: 45,
    cardio: true,
    strength: false,
    flexibility: false,
    distance: 11,
    feeling: 3,
    perceivedExertion: 6,
  },
  {
    id: '0002',
    name: 'Test 2',
    date: new Date(2021, 4, 12, 12, 30, 4).toISOString(),
    duration: 45,
    cardio: true,
    strength: true,
    flexibility: true,
    distance: 10,
    feeling: 3,
    perceivedExertion: 6,
  },
  {
    id: '0003',
    name: 'Test 3',
    date: new Date(2021, 4, 4, 16, 40, 57).toISOString(),
    duration: 45,
    cardio: true,
    strength: false,
    flexibility: true,
    distance: 10,
    feeling: 3,
    perceivedExertion: 6,
  },
  {
    id: '0004',
    name: 'Test 4',
    date: new Date(2021, 4, 1, 9, 30, 13).toISOString(),
    duration: 45,
    cardio: false,
    strength: false,
    flexibility: true,
    distance: 10,
    feeling: 3,
    perceivedExertion: 6,
  },
  {
    id: '0005',
    name: 'Test 5',
    date: new Date(2021, 3, 20, 12, 30, 43).toISOString(),
    duration: 45,
    cardio: true,
    strength: true,
    flexibility: false,
    distance: 10,
    feeling: 3,
    perceivedExertion: 6,
  },
];
